meta:
  engine: 4.0.4
  version: 3.0.0
  author: Guido Bartolucci <guido@bartolucci.org>
units:
  th: 2.4 # This is the standard distance between through-hole components (0.1")
points:
  rotate: -20
  mirror:
    ref: thumbfan_far_top
    distance: 25
  zones:
    matrix:
      anchor:
        rotate: 5
        shift: [100, -100]
      key:
        tags: [core]
      columns:
        farpinky.key:
          col_net: col1
        pinky.key:
          col_net: col2
        ring.key:
          stagger: 12
          col_net: col3
        middle.key:
          stagger: 5
          col_net: col4
        index.key:
          stagger: -6
          col_net: col5
        inner.key:
          stagger: -2
          col_net: col6
      rows:
        bottom:
          row_net: row3
          mirror.row_net: row3r
        home:
          row_net: row2
          mirror.row_net: row2r
        top:
          row_net: row1
          mirror.row_net: row1r
    thumbfan:
      key:
        tags: [thumbfan]
      anchor:
        ref: matrix_middle_bottom
        shift: [5.5, -25]
      columns:
        tucky.rows.top: $unset
        near.rows.top: $unset
        tucky.key:
          splay: -5
          col_net: col1
        near.key:
          splay: -15
          origin: [-9.5, -9.5]
          col_net: col2
        home:
          key:
            splay: -15
            origin: [-9.5, -9.5]
          rows:
            thumb.col_net: col3
            top.col_net: col6
        far:
          key:
            splay: -15
            origin: [-9.5, -9.5]
          rows:
            thumb.col_net: col4
            top.col_net: col5
      rows:
        thumb:
          row_net: row4
          mirror.row_net: row4r
        top:
          row_net: row4
          mirror.row_net: row4r
outlines:
  raw:
    - what: rectangle
      where: true
      size: [u, u]  
      fillet: 2
